### ISSUE TITLE
Make compatible to latest AngularJS Version

### ISSUE THREAD

**Issue by asim-qburstian** [yaru22/angular-hovercard#4]
The old version is making problem with my latest projects. I think it will be good to change the version of angular from 1.2.10 to minimum 1.3.4.

**Comment by yaru22** [comment]
Hi @asim-qburstian, I just relaxed the dependency requirement from "1.2.10" to "^1.2.10" so "1.3.4" should be covered as well. Let me know if you still encounter any other problems.

**Comment by asim-qburstian** [comment]
Thanks. I will let know if there is any other problem.
